module two{
    struct Meter {
        float init_value;
        long id;
        float voltage;
        float current;
        float power;
        float frequency;
        float pf;
        long status;
        long padding;
    };
    struct Relay {
        float init_value;
        long id;
        long status;
        long padding1;
        long padding2;
    };
};
